version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twxplore-geo-app
  gui:
    build:
      context: .
      dockerfile: gui/Dockerfile
    container_name: twxplore-geo-gui
    ports:
      - 127.0.0.1:8081:80
  twks-server:
    container_name: twks-server
    environment:
      JAVA_OPTIONS: "-Dtwks.extcp=/extcp -Dtwks.dump=/dump -Dtwks.enableGeoSPARQL -Dtwks.extfs=/extfs -Dtwks.initialNanopublicationFilePath=/geo-data/loaded/dsa/features.ttl.bz2,/geo-data/loaded/reverse_beacon/features.ttl.bz2,/geo-data/loaded/tiger_line/features.ttl.bz2,/geo-data/loaded/uls/features.ttl.bz2 -Dtwks.tdbLocation=/data -Xmx8g"
    image: tetherlessworld/twks-server
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./data/geo:/geo-data:ro
