version: 2.1
jobs:
  scala:
    working_directory: ~/project
    docker:
      # First image is used to execute the steps
      - image: circleci/openjdk:11
      - image: tetherlessworld/twks-server:latest
        name: twks-server
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Build and test
          command: |
            sbt package test
      - store_test_results:
          path: target/test-reports
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - slack/status
  ts:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: gui-dependency-cache-v1-{{ checksum "gui/package.json" }}
      - run:
          command: |
            cd gui
            npm install
      - save_cache:
          key: gui-dependency-cache-v1-{{ checksum "gui/package.json" }}
          paths:
            - ./node_modules
      - run:
          command: |
            cd gui
            npm run build-development
      - slack/status
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - scala
      - ts
